### ISSUE TITLE
Publications from bib file

### ISSUE THREAD

**Issue by sahiljhawar** [sinaatalay/RenderCV#105]
Instead of manually adding the publications, there should be an option to input the bib file and fetch the relevant data and use that to build the publications section. This will come handy when a user a long list of publications

**Comment by sahiljhawar** [comment]
Instead of DOI, there should be URL or another generic keyword, in order to add not yet published articles which are under peer review (arXiv). I know arXiv also gives DOI, but it is more intuitive for people just to use the arXiv identifier instead of the DOI.

or a different approach would be:

In the publications sections, one can give the path to `bib` file. And then for `markdown` it needs to be handled by the `markdown` parser and for latex it can be directly handeled by the Texlive (I dont know if it is possible at all since LaTeX is generated from the Markdown file)

**Comment by sinaatalay** [comment]
Thank you! In the next release, `url` field will be available as an alternative to `doi` for PublicationEntry.

Using `bib` files to get publications is outside the scope of this project, maybe another Python script could be written to convert `bib` files into RenderCV YAML format.

**Comment by sinaatalay** [comment]
RenderCV v1.11 has `url` field for the `PublicationEntry` and has been released,

**Comment by sahiljhawar** [comment]
@sinaatalay I have added the conversion for `bib` to `yml` as per your format. Maybe take a look and see if you want to merge? I haven't included this in your code yet, I couldn't understand how to do it. Here's the repo: https://github.com/sahiljhawar/bib2yaml-for-rendercv

**Comment by sinaatalay** [comment]
Thank you! I think it's best to have this in another script. We could have added a new CLI command (`rendercv convert-from-bib example.bib`), but it would have added new dependencies and a new thing to maintain, which is not really in the scope of the project.

If you would like:

- You could add this to the[ User Guide's FAQ](https://docs.rendercv.com/user_guide/faq/) and link your script. You can send a pull request with updated docs (check out the developer guide for docs).
- Also, you could open a discussion about this so that people can see it.

**Comment by sahiljhawar** [comment]
This does not add extra heavy dependencies. Just two more. I would suggest this script for the CLI command. Rest is up to you, you are the BDFL :')
