### ISSUE TITLE
Incorrect fonts used in engineeringresumes theme

### ISSUE THREAD

**Issue by TheColorDarkBlue** [sinaatalay/RenderCV#114]
#100

**Comment by sinaatalay** [comment]
Could you please elaborate? I don’t understand what you mean by incorrect fonts.

**Comment by TheColorDarkBlue** [comment]
> Could you please elaborate? I don’t understand what you mean by incorrect fonts.

From #100, 

- Update Bitstream Charter to [**XCharter**](https://ftp.snt.utwente.nl/pub/software/tex/fonts/xcharter/doc/xcharter-doc.pdf)

> The XCharter fonts are extensions of the Bitstream Charter fonts, adding oldstyle figures, superior figures and small caps in all styles.

- Remove unwanted fonts: ~~Latin Modern Serif, Latin Modern Sans Serif, Latin Modern Mono, Source Sans 3~~

**Comment by sinaatalay** [comment]
Sorry, I'm not quite following up on what this issue is about. Also, it doesn't seem like a `bug` to me, more like an `enhancement` request.

You need to clarify what you want precisely and explain the reasons behind it. The reasons are very important because that's how we will decide whether to do these things.

I see you want two things:

-  Remove available fonts from `engineeringresumes` theme.
-  Add a new font, `XCharter`.

Can you explain the reasons for each of these points?
