### ISSUE TITLE
Support for more languages

### ISSUE THREAD

**Issue by yuqiuwen** [sinaatalay/RenderCV#14]

**Comment by sinaatalay** [comment]
Hello, could you explain what kind of support you would like?

**Comment by AndreasKarasenko** [comment]
Necroing this issue because I had the same requirement today. It would be nice if a parameter could be passed to change the language of the headers. E.g. "Summary" --> "Zusammenfassung".

If it's not planned to ever add something like this here is a workaround:
Simply edit the .tex file that gets created, i.e. look for the sections and change the word in the curly braces to your language.
Then run the below snippet
`
from rendercv.renderer import latex_to_pdf
import pathlib
path = pathlib.Path("./rendercv_output/your_tex_file.tex")
latex_to_pdf(path)
`

**Comment by AndreasKarasenko** [comment]
For people that want to change the language: you can directly edit the tex file created after the render cli command. You can then use the latex_to_pdf function from this library to recreate the pdf. Simple regex can automate that as well. I just changed all the date related things to German, the headers can be translated directly in the yaml.

E.g.
```
from rendercv.renderer import latex_to_pdf
import pathlib

path = pathlib.Path("./rendercv_output/test_CV.tex")
latex_to_pdf(path)
```
Change the path to the path of your file and enjoy pls.

**Comment by sinaatalay** [comment]
Could you please post the same comment in issue #26 @AndreasKarasenko? Thank you very much for your contribution.
