### ISSUE TITLE
Add `rendercv_settings` field to the data model

### ISSUE THREAD

**Issue by sinaatalay** [sinaatalay/RenderCV#146]
In addition to the `cv`, `design`, and `locale_catalog` fields, we should include a new field called `rendercv_settings`.

`rendercv_settings` could contain all the CLI options (like output folder name, pdf path, etc.) and other settings like discussed in #139 and #144.

**Comment by sinaatalay** [comment]
#164

**Comment by akib1689** [comment]
I'm trying to implement this. I'll let you know when this is implemented

**Comment by sinaatalay** [comment]
Thank you very much! Let me know if you need any guidance.

**Comment by akib1689** [comment]
**Question:**
What would be the current cli options for the rendering?

potentials options:
- Remove the cli option altogether for `render` only.
- maintain a hierarchy say if now args is provided from the cli then we take from the `rendercv_render` block. (which is also an optional block btw).

**Comment by sinaatalay** [comment]
> What would be the current cli options for the rendering?

All the CLI options are listed in the [documentation](https://docs.rendercv.com/user_guide/cli/).

> Remove the cli option altogether for render only.

What's the reason to remove CLI options?

> maintain a hierarchy say if now args is provided from the cli then we take from the `rendercv_render` block. (which is also an optional block btw).

Yes, CLI options should always overwrite whatever is in the YAML file.

**Comment by akib1689** [comment]
> What's the reason to remove CLI options?

we now will have the ability to override the rendercv settings like this: `--rendercv_settings.no_html true` Then we have to maintain 3 levels of hierarchy.

Then when we use  `--rendercv_settings.no_html true` without `-nohtml` option. what would be the expected behaviour? I know this example the answer is simple should not be generated. but what if the provided configuration is conflicting. say with `pdf_path`. 

Because of this scenario I was considering removing the cli option from render portion only. 

But, to me the 2nd option sounds good choice.
