### ISSUE TITLE
Handling of $ or ’ in work experience

### ISSUE THREAD

**Issue by brrr123** [sinaatalay/RenderCV#154]
When a work description contains special characters like $ or ’ it fails to render the output. 
Adding \\ in front of the special characters in the YAML file seems to solve this error. Is it possible to escaping of special characters to the rendering routine? 

An error occurred:

RenderCV's built-in TinyTeX binaries couldn't render this LaTeX file into a PDF. This could be caused by one of two
reasons:

1- The theme templates might have been updated in a way RenderCV's TinyTeX cannot render. RenderCV's TinyTeX is
minified to keep the package size small. As a result, it doesn't function like a general-purpose LaTeX distribution.
2- Special characters, like Greek or Chinese letters, that are not compatible with the fonts used or RenderCV's TinyTeX
might have been used.

However, this issue can be resolved by using your own LaTeX distribution instead of the built-in TinyTeX. This can be
done with the '--use-local-latex-command' option, as shown below:

rendercv render --use-local-latex-command lualatex John_Doe_CV.yaml

If you ensure that the generated LaTeX file can be compiled by your local LaTeX distribution, RenderCV will work
successfully. You can debug the generated LaTeX file in your LaTeX editor to resolve any bugs. Then, you can start
using RenderCV with your local LaTeX distribution.

If you can't solve the problem, please open an issue on GitHub.**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
Please provide a minimal YAML input as a code block for us to produce the same error.

**Screenshots**

**Comment by ktneely** [comment]
I was going to file a similar bug or enhancement to the effect of fixing the escaped characters in the Markdown output.  If a `$` is used and escaped with a `\`, then the Markdown version has the escape as well as the character.  This is also true of other common LaTeX declarations, such as `\textonehalf{}`.   It would be nice if the Markdown converter knew how to convert these to text, rather than bringing the code forward.

As to whether or not the conversion should occur from YAML to the `.tex` file or if it should happen from the YAML to the `.md` file is up to the project maintainers, IMHO.

**Comment by sinaatalay** [comment]
Sorry, I couldn't address this issue earlier. It will be fixed in the next release.

I was not intentionally escaping those characters to allow people to write math in their CVs. In the next release, they will all be escaped by default, except something is written between `$$` signs like this: `$$example$$.` Nothing will be escaped between them for math support.

**Comment by sinaatalay** [comment]
This issue has been fixed. It will be released soon. Thank you!
