### ISSUE TITLE
Getting issue with

### ISSUE THREAD

**Issue by VinayChaudhari1996** [sinaatalay/RenderCV#30]
**Describe the bug**
I am getting the following issue while using ```theme: sb2nov```
![image](https://github.com/sinaatalay/rendercv/assets/42869040/2df778cc-adcc-4e5b-851e-2d3d3bb7c74f)

**To Reproduce**
I ran the following cmd/steps:-
1) rendercv new "Alex"

2) Changed the theme name under design in yaml file
![image](https://github.com/sinaatalay/rendercv/assets/42869040/75eedc2e-a2c0-46f9-a10b-d8d4990e6a53)

3) rendercv render Alex_CV.yaml

**Screenshots**

![image](https://github.com/sinaatalay/rendercv/assets/42869040/39fce430-e07d-4c11-9964-c85a3a6a2476)

**Comment by sinaatalay** [comment]
Hello, this is actually not a bug, but the error message could have been clearer. I will fix that in the next release.

Each theme has different options. `show_timespan_in` is only a valid option for the `classic` theme. Therefore, when you changed the theme to `sb2nov`, it complained because `sb2nov` doesn’t have that option.

Please check the tip about JSON Schema that is given in the [user guide](https://sinaatalay.github.io/rendercv/user_guide/#generating-the-input-file). It is very helpful.

**Comment by VinayChaudhari1996** [comment]
1) So what will be the quick fix , for sb2nov for now

2) Some ideas :- 
Can you create a flag for theme name itself while creating a yaml file through cmd ? so yaml file will create accordingly as per theme

Ex:- rendercv new "Alex" --sb2nov

**Comment by sinaatalay** [comment]
Hello, in the next release, there will be a theme option for the `rendercv new` command. Thank you for the suggestion!
