### ISSUE TITLE
Preview custom themes during development

### ISSUE THREAD

**Issue by naskio** [sinaatalay/RenderCV#44]
I want to know if there's a way to preview a custom theme during development, if not then it would be great to provide a way to achieve that.

**Comment by sinaatalay** [comment]
Hello! Unfortunately, this is not possible because $\LaTeX$ itself doesn't have this feature. You need to run RenderCV again whenever you want to see the updated version.

Additionally, I suggest developing a new theme with a $\LaTeX$ editor first, like [Overleaf](https://www.overleaf.com). And when you're happy with the result, you can move the code to RenderCV. For example, [the `classic` theme is already in Overleaf](https://www.overleaf.com/latex/templates/rendercv-classic-theme/szbrrwnrfksk), and you can play with it to develop your custom theme.
