### ISSUE TITLE
Option to switch order and bold/italic to Position and Company fields

### ISSUE THREAD

**Issue by andrea-gasparini** [sinaatalay/RenderCV#45]
First of all thanks a lot for the great project!

When adding a new entry in the Experience section of my cv I usually prefer to put more emphasis on the role I have than on the name of the company, as it is on the `moderncv` theme (`Position` field first and in bold, `Company` field second).

![image](https://github.com/sinaatalay/rendercv/assets/36965464/efb6b4dc-2ee6-46bc-b304-eb30f512fa9d)

The other themes work the other way around, so if I want to use the `classic` theme I have to switch the values of the `Position` and `Company` fields to get the same result:

![image](https://github.com/sinaatalay/rendercv/assets/36965464/fa9d6b85-7836-4ef9-8937-91a97a3213f4)

instead of the original setting:

![image](https://github.com/sinaatalay/rendercv/assets/36965464/563d052f-70d4-42b4-8844-7149ed8620f1)

I feel like it would be nice to have an option to simply choose the order of the two fields and have it consistent when one switches theme.

**Comment by sinaatalay** [comment]
Thank you for the compliment and the idea!

I agree; it would be nice to have this feature. I have an idea about how to approach this and will implement it in the next releases. I will comment on this issue again when I decide how this feature will look on the user side.

And for now, as a quick solution, you could use [`NormalEntry`](https://sinaatalay.github.io/rendercv/user_guide/#normal-entry) and in the `name` field, type the company and position manually with Markdown syntax. Even though the documentation shows only the `date` field, you can use `start_date` and `end_date` with `NormalEntry` as well.

**Comment by andrea-gasparini** [comment]
> I agree; it would be nice to have this feature. I have an idea about how to approach this and will implement it in the next releases. I will comment on this issue again when I decide how this feature will look on the user side.

Nice, thank you for taking it into consideration. Let me know if you need any help on that, I'd be glad to work on it.

**Comment by sinaatalay** [comment]
Thank you! When it's clear how to approach this, I will let you know.

**Comment by sinaatalay** [comment]
Hello, after thinking about this, I decided not to implement this feature due to the reasons below:

- Specifying when the company or position comes first wouldn't be very straightforward in the YAML file. It could break the clarity and ease of the data model.
- Even though it doesn't seem like it, RenderCV doesn't care about the data but what it renders to the screen. So, each data model has a very clear definition of what it is going to render on the screen, and users should interpret data models as not data storage structures but rendering structures. If you want to switch the order of the company and position, you can simply change the values of the `company` and `position` keys accordingly.

But I implemented the following:

- Now, all the themes are consistent with their `ExperienceEntry`'s.
- Users can now normalize bold or italicized texts by overwriting the style with Markdown syntax. For example, if the `company` field is bold, writing `company: **Your Company**` will print `Your Company` in normal format.

Please comment on this issue if you think I am missing something. Thank you for the issue and ideas!

**Comment by sinaatalay** [comment]
Oh, sorry, after thinking about it even more, I realized there might be a very great way of doing this, which might make RenderCV a lot more powerful.

If you are willing to implement it, that would be greatly appreciated.

Here is what's on my mind:

Each theme of RenderCV is actually a folder with these files:

```
├── classic
│   ├── Preamble.j2.tex
│   ├── Header.j2.tex
│   ├── EducationEntry.j2.tex
│   ├── ExperienceEntry.j2.tex
│   ├── NormalEntry.j2.tex
│   ├── OneLineEntry.j2.tex
│   ├── PublicationEntry.j2.tex
│   ├── TextEntry.j2.tex
│   ├── SectionBeginning.j2.tex
│   └── SectionEnding.j2.tex
```

Each file corresponds to either a RenderCV entry type or a specific part of the $\LaTeX$ CV code. So, let's say you would like to see the position field before the company field in the ExperienceEntry type. Then, you would need a different `ExperienceEntry.j2.tex` file. For cases like this:

A user should be able to create this folder next to the RenderCV input file.

``` { .sh .no-copy }
├── classic
│   └── ExperienceEntry.j2.tex
└── Your_Full_Name_CV.yaml
```

Then RenderCV should assume: "User provided the classic theme's `ExperienceEntry.j2.tex` file, so I should overwrite the default experience entry with this one". 

This feature would make RenderCV an actual $\LaTeX$ CV framework. Also, it should be very straightforward to implement.

Also,  this addresses exactly your point, @c2tz.

**Comment by c2tz** [comment]
Yes, that's what's currently used on Hugo's papermod theme and also on material mkdocs in a "overrides" folder.

I also find that papermod plays a lot on this and it brings a real plus in terms of customisation compared to other themes which are quite limited. 

As for the implementation, I'll leave that up to you 🫡

I've switched back to overleaf for the moment because I use latexlua to have certain things a bit different (compilation date and time with TZ UTC+1, .latexmkrc and above all fontspec which is much simpler).

But the idea is very good

**Comment by sinaatalay** [comment]
Hello, everyone; it turns out the current code base already has this feature. I accidentally implemented it for custom themes. You can override the themes as discussed above. Also, @c2tz, you can now run `lualatex` with `rendercv==1.6`.

**Comment by c2tz** [comment]
> Hello, everyone; it turns out the current code base already has this feature. I accidentally implemented it for custom themes. You can override the themes as discussed above. Also, @c2tz, you can now run `lualatex` with `rendercv==1.6`.

Super cool, I'll be testing this soon

**Comment by resting-dove** [comment]
Thanks for the great package! I just wanted to mention that the nice mechanism for customizing the templates mentioned here doesn't work on Windows. I assume because of the backslashes in the paths.

**Comment by sinaatalay** [comment]
> Thanks for the great package! I just wanted to mention that the nice mechanism for customizing the templates mentioned here doesn't work on Windows. I assume because of the backslashes in the paths.

Thank you! That's strange. RenderCV is being tested on Windows. Are you sure the files are in the right place (see [docs](https://docs.rendercv.com/user_guide/#overriding-built-in-themes))? I will test it manually soon.

**Comment by resting-dove** [comment]
I tried it again and now it works. Sorry for bothering you and thanks so much for the quick response!

**Comment by EsEnZeT** [comment]
> Hello, after thinking about this, I decided not to implement this feature due to the reasons below:
> 
> * Specifying when the company or position comes first wouldn't be very straightforward in the YAML file. It could break the clarity and ease of the data model.
> * Even though it doesn't seem like it, RenderCV doesn't care about the data but what it renders to the screen. So, each data model has a very clear definition of what it is going to render on the screen, and users should interpret data models as not data storage structures but rendering structures. If you want to switch the order of the company and position, you can simply change the values of the `company` and `position` keys accordingly.
> 
> But I implemented the following:
> 
> * Now, all the themes are consistent with their `ExperienceEntry`'s.
> * Users can now normalize bold or italicized texts by overwriting the style with Markdown syntax. For example, if the `company` field is bold, writing `company: **Your Company**` will print `Your Company` in normal format.
> 
> Please comment on this issue if you think I am missing something. Thank you for the issue and ideas!

Looks like that logic was removed and it's not working anymore.
