### ISSUE TITLE
3rd party fonts are missing licenses

### ISSUE THREAD

**Issue by michael-sbarra** [sinaatalay/RenderCV#7]
1. Source-sans [OFL 1.1](https://github.com/adobe-fonts/source-sans/blob/release/LICENSE.md)
2. Roboto [Apache 2](https://github.com/googlefonts/roboto/blob/main/LICENSE)
3. EB-Garmand [OFL 1.1](https://github.com/georgd/EB-Garamond/blob/master/COPYING)

**Comment by sinaatalay** [comment]
Thank you for finding this! It's my first published code, and it didn't occur to me to add licenses for the fonts.

**Comment by michael-sbarra** [comment]
@sinaatalay No problem. Also, it would be more scalable to add 3rd party fonts (and SW in general) as dependencies, rather than bundle it with your software. Then in the setup phase, the 3rd party stuff is downloaded. It is recommended to still list all the 3rd party software that your software uses (with their licenses), but at least you would not be directly distributing it. I'm also looking into how to use an existing TinyTex distribution so it can be removed from this project. I found [`pytinytex`](https://pypi.org/project/pytinytex/), but since it is just a wrapper a post-install command needs to be run to actually download TinyTex.

**Comment by sinaatalay** [comment]
@michael-sbarra I agree. It would be more elegant to have fonts and TinyTeX as dependencies. Including TinyTeX in the repository makes it seem like there are more lines of code than there actually are, and it's inappropriate to have it in the source code. The problem is that I was able to reduce the size of TinyTeX from approximately 500 MB to about 100 MB. It would be great if we could allow users to download only the required part of TinyTeX during installation.

**Comment by sinaatalay** [comment]
@michael-sbarra Maybe we could open another issue about removing TinyTeX and fonts from the repository and keep it open until we come up with a solution?

**Comment by michael-sbarra** [comment]
Created #8
